### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KOSTROMARUSSIA** [badboysm890/Adfly-Bot#2]
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Adfly-Bot/main.py", line 31, in <module>
    fun()
  File "/home/kali/Adfly-Bot/main.py", line 19, in fun
    driver = webdriver.Firefox(options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
`

**Comment by KOSTROMARUSSIA** [comment]
pip3 install selenium
Requirement already satisfied: selenium in /usr/lib/python3/dist-packages (4.0.0a1)
